
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 219, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 221, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 221, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 221, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 221, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 219, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 219, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
