
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 219, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 221, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 221, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 221, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 221, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 219, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 219, 'name': 'excluir_plot_serie', 'type': 'ValueError', 'message': ValueError('list.remove(x): x not in list',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\libs\\MLP\\mlp_lib.py', 'lineno': 88, 'name': 'fit', 'type': 'ValueError', 'message': ValueError('Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.',)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\series_temporais.py', 'lineno': 172, 'name': 'converter_tempo', 'type': 'TypeError', 'message': TypeError("can't multiply sequence by non-int of type 'NoneType'",)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 201, 'name': 'box_plot', 'type': 'TypeError', 'message': TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\series_temporais.py', 'lineno': 172, 'name': 'converter_tempo', 'type': 'TypeError', 'message': TypeError("can't multiply sequence by non-int of type 'NoneType'",)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 203, 'name': 'box_plot', 'type': 'TypeError', 'message': TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\series_temporais.py', 'lineno': 172, 'name': 'converter_tempo', 'type': 'TypeError', 'message': TypeError("can't multiply sequence by non-int of type 'NoneType'",)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 201, 'name': 'box_plot', 'type': 'TypeError', 'message': TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 201, 'name': 'box_plot', 'type': 'AttributeError', 'message': AttributeError("module 'app.libs.estatisticas' has no attribute 'reshape_array'",)}
{'filename': 'C:\\Users\\Pain panda\\Projeto_extensao\\Codigo_fonte\\app\\processamento\\series_temporais\\processamento.py', 'lineno': 201, 'name': 'box_plot', 'type': 'ValueError', 'message': ValueError('range() arg 3 must not be zero',)}
